version: "3.3"

services:
  database:
    image: database
    container_name: database
    build:
      context: ./local-dev/database/
      dockerfile: Dockerfile
    volumes:
      - ${HOME}/couchdb/data:/opt/couchdb/data
    network_mode: "host"
  metcap-api:
    image: metcap-api
    container_name: metcap-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/local-dev/database/config:/opt/metcap/etc
      - ${PWD}:/app/metcap-api
    network_mode: "host"
