version: "3.3"

services:
  metcap-db:
    image: metcap-db
    container_name: metcap-db
    build:
      context: ./local-dev/database/
      dockerfile: Dockerfile
    volumes:
      - ${HOME}/metcap/couchdb/data:/opt/metcap/couchdb/data
    network_mode: "host"
  metcap-api:
    image: metcap-api
    container_name: metcap-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/local-dev/database/config:/opt/metcap/etc
      - ${HOME}/metcap/data_sources:/opt/metcap/data_sources
      - ${PWD}:/app/metcap-api
    network_mode: "host"
